
--CREATING CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
CID INT PRIMARY KEY,
CNAME VARCHAR(100),
CITY VARCHAR(100)
)

--INSERTING VALUES INTO CUSTOMERS TABLE

INSERT INTO CUSTOMERS VALUES(10,'SOUJANYA','KOPPAL'),
(11,'SOUMYA','BAGYANAGR'),
(3,'RAHUL','GADAG'),
(4,'SHANKARU','HUBLI'),
(5,'SHARANU','MYSORE'),
(6,'CHANDRU','BELLARY'),
(7,'SHILPA','BANGLORE'),
(8,'JAGRUTHI','MANGLORE')


--CREATING ORDERS TABLE 
CREATE TABLE ORDERS (
ORDERID INT PRIMARY KEY,
CID INT REFERENCES CUSTOMERS(CID),
ORDERDATE DATE,
AMOUNT FLOAT
)


--INSERTING VALUES INTO ORDERS TABLE
INSERT INTO ORDERS VALUES(112,NULL,'07/22/2025',10012),
(102,1,'07/23/2025',15000),
(103,4,'07/24/2025',1200),
(104,2,'07/26/2025',3000),
(105,1,'07/27/2025',4500),
(106,3,'07/29/2025',2500),
(107,6,'07/31/2025',1500),
(108,8,'08/1/2025',1399),
(109,7,'8/12/2025',1999),
(110,5,'8/11/2025',9999)

--SHOW CUSTOMERS WHO HAVA PLACED ORDERS

SELECT C.CID,O.ORDERID,C.CNAME,O.ORDERDATE,O.AMOUNT
FROM CUSTOMERS C INNER JOIN ORDERS O 
ON C.CID=O.CID

-- SHOW ALL CUSTOMERS WITH THEIRE ORDERS IF AVAILABLE NULL IS NO ORDERS

SELECT C.CID,C.CNAME,O.ORDERID,O.ORDERDATE,O.AMOUNT
FROM CUSTOMERS C LEFT JOIN ORDERS O
ON C.CID=O.CID

--SHOW ALL ORDERS ,WITH THERE CUSTOMER DETAILS ,NULL IF NO MATCHING CUSTOMERS
SELECT C.CID,C.CNAME,O.ORDERID,O.ORDERDATE,O.AMOUNT
FROM CUSTOMERS C RIGHT JOIN ORDERS O
ON C.CID=O.CID

--SHOW ALL CUSTOMERS AND ALL ORDERS WITH NULL WHERE NO MATCH EXIST

SELECT C.CID,C.CNAME,O.ORDERID,O.ORDERDATE,O.AMOUNT
FROM CUSTOMERS C FULL JOIN ORDERS O
ON C.CID=O.CID

--HERE IT SHOWS THE JOIN EXAMPLE USING ADVENTUREWORS2022 DATABASE

--BELOW ARE THE TABLES WHICH CONTAINS PERSON DATA IN DIFFERENT TABLES
SELECT * FROM [Person].[Person]
SELECT * FROM [Person].[EmailAddress]
SELECT * FROM [Person].[PersonPhone]
SELECT * FROM [Person].[Address]
SELECT * FROM [Person].[AddressType]

--JOINING MULTIPLE TABLES TO GET ALL THE REQUIRED PERSON DETAILS
SELECT  PP.BusinessEntityID,
		PP.FirstName,
		PP.LastName,
		PE.EmailAddress,
		PH.PhoneNumber,
		PA.AddressLine1,
		PA.City,
		PA.PostalCode
FROM [Person].[Person] PP INNER JOIN [Person].[EmailAddress] PE
		ON PP.BusinessEntityID=PE.BusinessEntityID
INNER JOIN [Person].[PersonPhone] PH 
		ON PP.BusinessEntityID=PH.BusinessEntityID
INNER JOIN [Person].[BusinessEntityAddress] PBEA
		ON PP.BusinessEntityID=PBEA.BusinessEntityID
INNER JOIN [Person].[Address] PA
		ON PBEA.AddressID=PA.AddressID